version: "3"

volumes:
  influxdb-data:
  node-red-data:

networks:
  default:

services:
  node-red:
    image: nodered/node-red:latest-12
    restart: always
    volumes:
      - node-red-data:/data
    ports:
      - 1880:1880

  proxy:
    image: dhogborg/influx-cors-proxy:latest
    platform: linux/amd64
    restart: always
    ports:
      - 9086:9086
    environment:
      - TARGET=http://influxdb:8086

  verisure-mqtt:
    image: mountaindude/verisure-mqtt:latest
    restart: always
    depends_on:
      - mqtt
    # Set debug flag to true to output all received info to console.
    # False will limit output to only mention that a query to the Verisure API is made
    environment:
      - "VERISURE_DEBUG=true"
      - "MQTT_BROKER_HOST=house-sensors_mqtt_1"
      - "MQTT_BROKER_PORT=1883"
      - "MQTT_ROOT_TOPIC=sensors/"
      - "VERISURE_USERNAME=${VERISURE_USERNAME}"
      - "VERISURE_PWD=${VERISURE_PASSWORD}"

  mqtt:
    image: eclipse-mosquitto:2
    restart: always
    volumes:
      - ${PWD}/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
      - 9001:9001
  
  dashboard:
    image: dhogborg/house-dashboard:latest
    platform: linux/amd64
    restart: always
    depends_on:
      - influxdb
    ports:
      - 80:80


  influxdb:
    image: influxdb:1.8.10-alpine
    platform: linux/amd64
    restart: always
    volumes:
      - influxdb-data:/var/lib/influxdb
      - ${PWD}/backup:/backup
    environment:
      - INFLUXDB_HTTP_FLUX_ENABLED=true
    ports:
      - 8086:8086

  influx_worker:
    image: influxdb:1.8-alpine
    entrypoint: /bin/bash
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - influxdb-data:/var/lib/influxdb
      - ${PWD}/workdir:/workdir

  chronograf:
    image: chronograf:1.9.3
    restart: always
    depends_on:
      - influxdb
    command: [chronograf, --influxdb-url, "http://influxdb:8086"]
    ports:
      - 8888:8888
  